### ISSUE TITLE
Loss function of the classifier

### ISSUE THREAD

**Issue by XiaoqiangZhou** [zhangqianhui/GazeCorrection#1]
Hello, this is an interesting work about eye's inpainting. Could you please answer me a few questions? 

It seems you use a different symbol for the classifier's loss in equation (3), i.e., positive for data from X and negative for data from X_wave. May I ask why?  

Are you enforcing this classifier to learn not only the left-or-right classification but also the real-or-fake classification? I think it is rellay strange, because we hope this classfier to classify eyes from X_wave oppositely? (I mean, for x from X_wave, if the classifier classifies left eye as right eye, and right eye as left eye, it will get a smaller loss than classify these eyes' position correctly?)

Note: all of the classifiers mentioned above denote the left-or-right classifier.

**Comment by zhangqianhui** [comment]
left-or-right classifier  to perform self-supervised learning.
