### ISSUE TITLE
preformnce in

### ISSUE THREAD

**Issue by llf1234** [zhangqianhui/GazeCorrection#2]
excellent work! when i test the trained model in NewGanDataset(Y) the performance is good, but i test in my own dataset,the performance drop drasticly,can you tell me the preprocess method you used. appreciate for your reply!

**Comment by zhangqianhui** [comment]
You should align your dataset just like NewGazeDataset.

**Comment by llf1234** [comment]
Thank you for your reply can you tell me which detection algorithm or alignment algorithm you choosed，when i ues MTCNN，the box is not always square。but the face box h and w in celeb id dataset is square.

**Comment by zhangqianhui** [comment]
by face feature point

llf1234 <notifications@github.com> 于2019年8月1日周四 下午7:21写道：

**Comment by ALONGNEU** [comment]
Hi @llf1234 ,  do you know how to align the dataset for now?
