### ISSUE TITLE
Key discriminator/dis_FC1/Matrix not found in checkpoint

### ISSUE THREAD

**Issue by gao-shi** [zhangqianhui/GazeCorrection#4]
hello，when i test on my own image dataset, i meet this error~  it seems the ckpt is not same with current architecture of network.

**Comment by zhangqianhui** [comment]
I would test it right now.

**Comment by gao-shi** [comment]
my tensorflow version=1.7，  and the error locate at restoring model，like this:
`NotFoundError (see above for traceback): Key discriminator/dis_FC1/Matrix not found in checkpoint
	 [[Node: save/RestoreV2 = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]
	 [[Node: save/RestoreV2/_133 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_138_save/RestoreV2", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]
`

**Comment by zhangqianhui** [comment]
the ckpt is for self-guided encode network, not for discriminator.

**Comment by gao-shi** [comment]
It means that i have to use this model to restore self-guided encode network, and train the Generator and Discriminator on my own, then i can test images

**Comment by zhangqianhui** [comment]
Yes

**Comment by gao-shi** [comment]
thx！   But training speed is a little slow,. One GPU is used but i have 8 GPUs。

**Comment by gao-shi** [comment]
By the way , can you offer the trained main network model ~~

**Comment by zhangqianhui** [comment]
sorry, I have the changed the model but the code has not been updated.
