### ISSUE TITLE
Question About Training Time On My Own Dataset

### ISSUE THREAD

**Issue by ftaker887** [zhangqianhui/GazeCorrection#7]
I have a general question about training time on my own dataset. On a single Tesla P100, how long can I expect it to train before getting acceptable results? I'm currently at 165000 iters and the eye area still looks very grainy. I don't know if this is a convergence issue or just apart of the training process. Should I train further or modify my target dataset? Thanks!

**Comment by zhangqianhui** [comment]
Sorry, Can you show one image of your dataset?

**Comment by ALONGNEU** [comment]
Hi @ftaker887 ,  do you know how to create the similar dataset from own data for now?
